version: '3'

services:
  mysql:
    image: mysql:8.0
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
    ports:
      - '3306:3306'
